/* groovylint-disable NestedBlockDepth */
pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }
        stage('Python Lint') {
            steps {
                script {
                    def dirs = sh(script: 'ls -d */', returnStdout: true).trim().split()
                    for (dir in dirs) {
                        def pythonFiles = sh(script: "find ${dir} -name 'app.py'", returnStdout: true).trim().split()
                        if (pythonFiles.size() > 0) {
                            sh "python3 -m pylint --fail-under=5 ${pythonFiles.join(' ')}"
                        }
                    }
                }
            }
        }
        stage('Vulnerabilities scanning') {
            steps{
                sh 'python3 -m safety check'
            }
        }
    }
}
